ALTER TABLE QUESTION ALTER COLUMN ID bigint NOT NULL;
ALTER TABLE `USER` ALTER COLUMN ID bigint NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN CREATER bigint NOT NULL;
ALTER TABLE COMMENT ALTER COLUMN COMMENTATOR bigint NOT NULL;
